version: '3.8'


services:
  python_app:
    build:
      context: . 
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: pycache
        target: /app/.cache
        volume:
          nocopy: true
    stdin_open: true
    tty: true
    shm_size: "512m"

volumes:
  pycache: {}

